### Support Vector Machines
- maximize distance to nearest point => margin
- kernel trick 
  - non-linear seperable => seperable
- parameters
  - kernel: rbf, linear
  - c: A low C makes the decision surface smooth, while a high C aims at classifying all training examples correctly.
  - gamma: how much influence a single training example has
- not applicable
  - too many features
  - too many noises
